dist: bonic
language: cpp
compiler: clang
sudo: required
addons:
  apt:
    packages:
    - git
    - cmake
    - ccache

branches:
  only:
  - master

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y clang-9 lld-9

install:
  - mkdir build

script:
  - cd build
  - SUF=-9 cmake ..
  - make
